version: '3'
services:
  server-registry:
    image: phongvanngo/dochero-server-registry:latest
    container_name: server-registry
    environment:
      - SERVER_PORT=${SERVER_REGISTRY_INTERNAL_PORT}
    ports:
      - ${SERVER_REGISTRY_PORT}:${SERVER_REGISTRY_INTERNAL_PORT}    

  account-service:
    image: phongvanngo/dochero-account-service:latest
    container_name: dochero-account-service
    environment:
      - SPRING_DATASOURCE_URL=${ACCOUNT_SERVICE_DB_URI}
      - SPRING_DATASOURCE_PASSWORD=${ACCOUNT_SERVICE_DB_PASSWORD}
      - SPRING_DATASOURCE_USERNAME=${ACCOUNT_SERVICE_DB_USERNAME}
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=${SERVER_REGISTRY_URL}
      - SERVER_PORT=${ACCOUNT_SERVICE_INTERNAL_PORT}
    ports:
      - ${ACCOUNT_SERVICE_PORT}:${ACCOUNT_SERVICE_INTERNAL_PORT}    
  
  api-gateway:
    image: phongvanngo/dochero-api-gateway:latest
    container_name: dochero-api-gateway
    environment:
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=${SERVER_REGISTRY_URL}
      - SERVER_PORT=${API_GATEWAY_INTERNAL_PORT}
    ports:
      - ${API_GATEWAY_PORT}:${API_GATEWAY_INTERNAL_PORT}   